Add pre-commit pipeline (#557)
Adds a pre-commit pipeline stage as well as the necessary container creation stage in order to enforce pre-commit hooks in the pipeline.

Signed-off-by: Hannes Baum <hannes.baum@cloudandheat.com>

diff --git a/gitlab-ci/krake-ci-pipeline.yml b/gitlab-ci/krake-ci-pipeline.yml
--- a/gitlab-ci/krake-ci-pipeline.yml
+++ b/gitlab-ci/krake-ci-pipeline.yml
@@ -38,40 +38,6 @@ pre-commit:
   only:
     - branches
     - merge_requests
-#  rules:
-#    - if: '$PRE_COMMIT_SKIP_BRANCH_PIPELINE && $CI_COMMIT_BRANCH'
-#      when: never
-#    - if: '$PRE_COMMIT_SKIP_MR_PIPELINE && $CI_PIPELINE_SOURCE == "merge_request_event"'
-#      when: never
-#    - if: '$PRE_COMMIT_AUTO_FIX_BRANCH_ONLY && $CI_PIPELINE_SOURCE == "merge_request_event"'
-#      variables:
-#        PRE_COMMIT_AUTO_FIX: ""
-#      when: on_success
-#      exists:
-#        - .pre-commit-config.yaml
-#    - if: '$PRE_COMMIT_DEDUPLICATE_MR_AND_BRANCH == "true" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
-#      when: never
-#    - if: '$PRE_COMMIT_AUTO_FIX_MR_ONLY && $CI_PIPELINE_SOURCE != "merge_request_event"'
-#      variables:
-#        PRE_COMMIT_AUTO_FIX: ""
-#      exists:
-#        - .pre-commit-config.yaml
-#      when: on_success
-#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "detached"'
-#      variables:  # we don't support autofix for merged_result or merge_train pipelines, configure branch fixing instead
-#        PRE_COMMIT_AUTO_FIX: ""
-#      exists:
-#        - .pre-commit-config.yaml
-#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
-#      exists:
-#        - .pre-commit-config.yaml
-#      when: on_success
-#    - if: '$CI_COMMIT_BRANCH'
-#      exists:
-#        - .pre-commit-config.yaml
-#      when: on_success
-#    - when: never
-
   variables:
     PRE_COMMIT_AUTO_FIX: "1"
     PRE_COMMIT_DEDUPLICATE_MR_AND_BRANCH: "true"
@@ -80,7 +46,6 @@ pre-commit:
   script: |
     status=0
     pre-commit run --all-files || status=$?
-    echo "Test 1"
     if [[ $status -ne 0 ]]; then
         if [[ -n "$CI_COMMIT_BRANCH" ]]; then
             git remote set-url origin "https://gitlab-ci-token:${PRE_COMMIT_ACCESS_TOKEN:-$CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
@@ -91,21 +56,20 @@ pre-commit:
             git remote set-url origin "https://gitlab-ci-token:${PRE_COMMIT_ACCESS_TOKEN:-$CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_MERGE_REQUEST_SOURCE_PROJECT_PATH}.git"
             git fetch origin
         fi
-        pre-commit run --all-files  # check the status passes now with autofix otherwise, it'll bail here
+        pre-commit run --all-files  # check the status passes now with autofix otherwise, it'll stop here
     else
-        exit 0  # we're all good, pipeline can proceed
+        exit 0
     fi
-    echo "Test 2"
+
     if [[ -z "$PRE_COMMIT_AUTO_FIX" ]]; then
         echo "No auto-fix enabled."
-        exit 1 # fail the job
+        exit 1 # Job will fail
     fi
 
-    # TODO: make email/username configurable
-    git config --global user.email "$GITLAB_USER_EMAIL"
-    git config --global user.name "pre-commit fix $GITLAB_USER_NAME"
-    # proceed with auto-fix
-
+    git config --global user.email "krake@cloudandheat.com"
+    git config --global user.name "Krake"
+    
+    # Proceed with auto-fix
     if [[ -z "$PRE_COMMIT_ACCESS_TOKEN" ]]; then
         echo "Auto-fix is enabled, but no pre-commit access token found." >> /dev/stderr
         echo "To enable automatic fixes, please create a project access token with repository write scope and set the PRE_COMMIT_ACCESS_TOKEN variable" > /dev/stderr
@@ -114,12 +78,12 @@ pre-commit:
 
     if [[ -n "$CI_COMMIT_BRANCH" ]]; then
         git add -u .
-        git commit -m "Automatic fixes from pre-commit CI job" -m "job url: $CI_JOB_URL"
+        git commit -m "Automatic fixes from pre-commit CI job" -m "job url: $CI_JOB_URL" -m "Signed-off-by: Krake <krake@cloudandheat.com>"
         git push
         exit 1
     elif [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
         git add -u .
-        git commit -m "Automatic fixes from pre-commit CI job" -m "job url: $CI_JOB_URL"
+        git commit -m "Automatic fixes from pre-commit CI job" -m "job url: $CI_JOB_URL" -m "Signed-off-by: Krake <krake@cloudandheat.com>"
         git push origin HEAD:"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
         exit 1
     else
